format = """
\n             [╱⠉⠉╱](bold fg:blue)\
\n         [⌎╲︶  ╱](bold fg:blue)[  ⟋❪](bold)\
\n[  ⡀⟋◠⣀⣀⣀⣀](bold)[⣀╱](bold fg:blue)[ ╎  ](bold)[❯∼∼](bold)[⟍◡◠◡◠◡◠◡](bold)[∼∼∼——————————————————┈◠◟⟍⟍](bold)
[╭❪](bold)\
[  ❖   ](bold bg:#cdd6f4 fg:black)\
[](bold bg:blue fg:#cdd6f4)\
[](bold fg:blue)\
[—┇—⸨ ](bold)\
$username\
[⋄@⋄](bold)\
$hostname\
[ ⸩—](bold)\
[◈❴](bold)\
$directory\
[❵◈—](bold)\
[](bg:#c28fff fg:#1e1e2e)\
[](bg:#907bbb fg:#c28fff)\
$time\
$git_branch\
$git_status\
$nodejs\
$rust\
$golang\
$php\
$aws\
$conda\
$dart\
$docker_context\
$elixir\
$elm\
$hg_branch\
$java\
$julia\
$nim\
$nix_shell\
$package\
$perl\
$python\
$ruby\
$swift\
[](bg:#655d8e fg:#907bbb)\
$cmd_duration\
[](bg:#47476f fg:#655d8e)[](bg:#1e1e2e fg:#47476f)[❯](bold)\
\n[╿ ⠁⟍◡⠉⠉⠉⠉](bold)[⠉╲](bold fg:blue)[ ╎  ](bold)[❯∽∽](bold)[⟋◠◡◠◡◠◡◠](bold)[∽∽∽——————————————————┈◡◜⟋⟋](bold)\
\n[╿        ](bold)[⌌╱︵  ╲](bold fg:blue)[  ⟍❪](bold)\
\n[╿            ](bold)[╲⣀⣀╲](bold fg:blue)\
\n$character\
$status
"""
#𐰢
#░▒▓
#᚛᚛
# First param ─┌﹎﹎﹎﹊﹊﹊
[username]
show_always = true
style_root = "bold fg:#ff8585"
style_user = "bold fg:#ffe8b5"
format = "[$user]($style)"
disabled = false

# Second param
[hostname]
disabled = false
format = "[$hostname]($style)"
ssh_only = false
style = "bold fg:#ff9393"
trim_at = "-"

[directory]
style = "bold fg:#aafff1"
format = "[ $path ]($style)"
truncation_length = 0
truncation_symbol = "repo: "
truncate_to_repo = true
#truncation_symbol = "../"
#🕉
#❖
#[directory.substitutions]
#"Documents" = " "
#"Downloads" = " "
#"Music" = " "
#"Pictures" = " "

[cmd_duration]
disabled = false
style = "bold fg:#ffe8b5 bg:#655d8e"
format = "[ ✦ $duration ]($style)"
min_time = 1

[sudo]
disabled = false

[character]
error_symbol = "[╰𐰢](bold red)"
success_symbol = "[╰𐰢](bold)"
#❯
[status]
disabled = false
format = '[$symbol$status_common_meaning$status_signal_name$status_maybe_int ]($style)'
map_symbol = true
pipestatus = true
symbol = "× (bold red)"

[time]
disabled = true
time_format = "%R" # Hour:Minute Format
style = "bold bg:#907bbb"
format = '[ ✦ $time ]($style)'

[git_branch]
symbol = ""
style = "bold bg:#907bbb"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bold bg:#907bbb"
format = '[($all_status$ahead_behind )]($style)'

[nodejs]
symbol = ""
style = "bold bg:#907bbb"
format = '[ $symbol ($version) ]($style)'

[rust]
symbol = ""
style = "bold bg:#907bbb"
format = '[ $symbol ($version) ]($style)'

[golang]
symbol = "ﳑ"
style = "bold bg:#907bbb"
format = '[ $symbol ($version) ]($style)'

[php]
symbol = ""
style = "bold bg:#907bbb"
format = '[ $symbol ($version) ]($style)'

[aws]
symbol = ""
style = "bold bg:#907bbb"
format = '[ $symbol ($version) ]($style)'

[conda]
symbol = ""
style = "bold bg:#907bbb"
format = '[ $symbol ($version) ]($style)'

[dart]
symbol = ""
style = "bold bg:#907bbb"
format = '[ $symbol ($version) ]($style)'

[docker_context]
symbol = ""
style = "bold bg:#907bbb"
format = '[ $symbol ($version) ]($style)'

[elixir]
symbol = ""
style = "bold bg:#907bbb"
format = '[ $symbol ($version) ]($style)'

[elm]
symbol = ""
style = "bold bg:#907bbb"
format = '[ $symbol ($version) ]($style)'

[hg_branch]
symbol = ""
style = "bold bg:#907bbb"
format = '[ $symbol ($version) ]($style)'

[java]
symbol = ""
style = "bold bg:#907bbb"
format = '[ $symbol ($version) ]($style)'

[julia]
symbol = ""
style = "bold bg:#907bbb"
format = '[ $symbol ($version) ]($style)'

[nim]
symbol = ""
style = "bold bg:#907bbb"
format = '[ $symbol ($version) ]($style)'

[nix_shell]
symbol = ""
style = "bold bg:#907bbb"
format = '[ $symbol ($version) ]($style)'

[package]
symbol = ""
style = "bold bg:#907bbb"
format = '[ $symbol ($version) ]($style)'

[perl]
symbol = ""
style = "bold bg:#907bbb"
format = '[ $symbol ($version) ]($style)'

[python]
symbol = ""
style = "bold bg:#907bbb"
format = '[ $symbol ($version) ]($style)'

[ruby]
symbol = ""
style = "bold bg:#907bbb"
format = '[ $symbol ($version) ]($style)'

[swift]
symbol = "ﯣ"
style = "bold bg:#907bbb"
format = '[ $symbol ($version) ]($style)'

