# image will be published to ghcr.io/<user>/<name>
name: catcat-os
# description will be included in the image's metadata
description: meow

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/bazzite-gnome-nvidia
image-version: 40 # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /

  - type: rpm-ostree
    repos:
      - https://copr.fedorainfracloud.org/coprs/atim/starship/repo/fedora-%OS_VERSION%/atim-starship-fedora-%OS_VERSION%.repo
      - https://repo.librewolf.net/librewolf.repo
    install:
      - firejail
      - firewall-config
      - https://github.com/fastfetch-cli/fastfetch/releases/latest/download/fastfetch-linux-amd64.rpm
      - fish
      - bat
      - eza
      - starship
      - micro
      - neovim
      - tmux
      - cowsay
      - cryfs
      - ptyxis
      - bleachbit
      - gnome-shell-extension-appindicator
      - gnome-shell-extension-blur-my-shell
      - gnome-shell-extension-caffeine
      - gnome-shell-extension-dash-to-dock
      - gnome-shell-extension-dash-to-panel
      - gnome-shell-extension-drive-menu
      - gnome-shell-extension-forge
      - gnome-shell-extension-gsconnect
      - gnome-shell-extension-user-theme
      - gnome-shell-extension-gamemode
      - awf-gtk2
      - awf-gtk3
      - awf-gtk4
      - librewolf
      - dosfstools
      - exfatprogs
      - gpart
      - gparted
      - dmraid
      - zstd
      - uresourced
      - irqbalance
      - bottles
      - goverlay
      - gamescope
      - gamemode
      - mangohud
      - vkBasalt
      - fluidsynth
    remove:
      # example: removing firefox (in favor of the flatpak)
      #- firefox
      #- firefox-langpacks
      #- gnome-initial-setup
      - fastfetch
      - ibus-libpinyin
      - ibus-libzhuyin
      - ibus-hangul
      - ibus-m17n
      - ibus-mozc
      - ibus-typing-booster
      - gnome-browser-connector
      - nautilus-gsconnect
      - plocate
      - gnome-shell-extension-just-perfection
      - openssh-askpass

  - type: script
    scripts:
      - cleanup.sh
      - setup.sh

  - type: default-flatpaks
    notify: true # Send notification after install/uninstall is finished (true/false)
    system:
      # If no repo information is specified, Flathub will be used by default
      # repo-url: https://dl.flathub.org/repo/flathub.flatpakrepo
      # repo-name: flathub
      # repo-title: "Flathub (system-wide)" # Optional; this sets the remote's user-facing name in graphical frontends like GNOME Software
      install:
      # Flatpak runtimes are not supported (like org.winehq.Wine//stable-23.08),
      # only normal flatpak applications are (like Floorp Lightning web browser in this example).
      # Installing different branches of the same Flatpak is not supported.
      remove:
      - org.mozilla.firefox
      - io.github.fastrizwaan.WineZGUI
      - it.mijorus.gearlever
      - org.gnome.NautilusPreviewer
      - org.gnome.TextEditor
      - io.github.nokse22.Exhibit

#  - type: gnome-extensions
#    install:
#      - Clipboard History
#      - Color Picker
#      - Compiz windows effect
#      - "CHC-E (Custom Hot Corners - Extended)"
#      - Hide Universal Access
#      - "[QSTweak] Quick Setting Tweaker"
#      - SettingsCenter
#      - Status Area Horizontal Spacing
#      - TopHat
#      - User Themes
#      - Vitals
#      - Window Gestures

  - type: fonts
    fonts:
      nerd-fonts:
        - FiraCode
        - Hack
        - JetBrainsMono
        - NerdFontsSymbolsOnly
      google-fonts:
        - Roboto
        - Open Sans

  - type: signing # this sets up the proper policy & signing files for signed images to work fully

