#!/usr/bin/env bash
MAJOR_VERSION=43
DEFAULT_TAG="latest"
AH_DATE="$(TZ="Asia/Kolkata" date +%Y\-%m\-%d\T%H\:%M\:%S\Z)"
DATESTAMP="$(TZ="Asia/Kolkata" date "+%Y%m%d")"
TIMESTAMP="$(TZ="Asia/Kolkata" date "+%H%M%S")"
DATETIMESTAMP="${DATESTAMP}.${TIMESTAMP}"
