#!/usr/bin/bash
source /usr/lib/catcat-os/bash-lib.sh

SYSTEM_LOAD_THRESHOLD_LOW=1.5
SYSTEM_LOAD_THRESHOLD_HIGH=3

set_power_profile() {
    log "INFO" "Setting power profile to: ${1}"
    local profile="${1}" ppd_profile tuned_profile

    case "${profile}" in
        performance)
            ppd_profile="performance"
            tuned_profile="catcat-performance"
            ;;
        balanced)
            ppd_profile="balanced"
            tuned_profile="catcat-balanced"
            [[ -n "${battery_power_state}" ]] && tuned_profile="catcat-balanced-battery"
            ;;
        powersave)
            ppd_profile="power-saver"
            tuned_profile="catcat-powersave"
            [[ -n "${battery_power_state}" ]] && tuned_profile="catcat-powersave-battery"
            ;;
        *)
            die "Unknown power profile: ${profile}"
            ;;
    esac

    has_cmd powerprofilesctl && powerprofilesctl set "${ppd_profile}"
    has_cmd tuned-adm && tuned-adm profile "${tuned_profile}"
}

previous_profile=""
while true; do
    system_load=$(cut -d' ' -f2 /proc/loadavg)
    battery_power_state=$(upower -d | awk '$1 == "state:" && ($2 == "charging" || $2 == "discharging") {print $2; exit}') || true
    override_profile="${OVERRIDE_POWER_PROFILE}"

    if [[ -n "${override_profile}" ]]; then
        target_profile="${override_profile}"
    elif [[ "${battery_power_state}" == "discharging" ]]; then
        target_profile="powersave"
    else
        if [[ $(echo "${system_load} < ${SYSTEM_LOAD_THRESHOLD_LOW}" | bc -l) -eq 1 ]]; then
            target_profile="powersave"
        elif [[ $(echo "${system_load} > ${SYSTEM_LOAD_THRESHOLD_LOW}" | bc -l) -eq 1 && $(echo "${system_load} < ${SYSTEM_LOAD_THRESHOLD_HIGH}" | bc -l) -eq 1 ]]; then
            target_profile="balanced"
        else
            target_profile="performance"
        fi
    fi

    if [[ "${target_profile}" != "${previous_profile}" ]]; then
        set_power_profile "${target_profile}"
        previous_profile="${target_profile}"
    fi

    sleep 30s
done
