#!/usr/bin/bash
source /usr/lib/catcat/funcvar.sh

# Remove useless logs, dirs or files
#

# System clean up
one_week=604800
if is_file_older ${one_week} "/etc/catcat-os/last_cleanup"; then
  /usr/bin/podman image prune -af
  /usr/bin/podman volume prune -f
  /usr/bin/systemd-tmpfiles --clean
  /usr/bin/flatpak --system uninstall --unused --assumeyes --noninteractive

  # Delete DNS logs older than 3 months (default}
  /usr/bin/localdnsctl -v --flush-logs

  date "+%a %b %d %H:%M:%S %Y" > /etc/catcat-os/last_cleanup
fi

# Run buttercare trim every 20 days
twenty_days=1728000
if is_file_older ${twenty_days} "/etc/catcat-os/buttercare.log"; then
  /usr/bin/buttercare -vv balance trim > /etc/catcat-os/buttercare.log
fi
