#!/bin/bash

check_internet_connection() {
    local max_attempts=3
    local sleep_time=2
    local attempt=1

    while (( attempt <= max_attempts )); do
        if curl --silent --head --fail "https://fedoraproject.org" > /dev/null; then
          return 0
        else
          echo "Internet connection is not available. Waiting..."
          sleep ${sleep_time}
          (( attempt++ ))
        fi
    done

    return 1
}

runtimes() {
  runtimes=(
'org.kde.KStyle.Kvantum'
'org.freedesktop.Platform.VulkanLayer.vkBasalt'
'org.freedesktop.Platform.VulkanLayer.gamescope'
'org.freedesktop.Platform.VulkanLayer.MangoHud'
'org.freedesktop.Platform.VulkanLayer.OBSVkCapture'
)
  for r in "${runtimes[@]}"; do
    flatpak install --system -y --noninteractive flathub $(flatpak search --columns=application,branch $r | awk '{print $1 "//" $2}')
  done
}

# Install or remove flatpaks if system is updated
if ! diff -q /etc/catcat-os/update_sha /etc/catcat-os/flatpak-list/previous_update_sha; then
  # Add and set flathub
  flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo --system
  flatpak remote-modify --system --prio=9 flathub

  # Install flatpaks in list
  INSTALL_LIST=($( sed '/^$/d; /^#/d' /etc/catcat-os/flatpak-list/install ))
  if check_internet_connection; then
    echo "Installing system flatpaks from config list (requires internet)"
#    flatpak install --system -y --noninteractive flathub ${INSTALL_LIST[@]}
    runtimes
    cat /etc/catcat-os/update_sha > /etc/catcat-os/flatpak-list/previous_update_sha
  fi

  # Remove flatpaks in list
  REMOVE_LIST=($( sed '/^$/d; /^#/d' /etc/catcat-os/flatpak-list/remove ))
  echo "Removing system flatpaks from config list"
  flatpak uninstall --system -y --noninteractive ${REMOVE_LIST[@]}
fi


# Flatpak overrides
if ! grep -q 'devices=!all' /var/lib/flatpak/overrides/global; then
flatpak override \
  --nodevice=all \
  --nofilesystem=host \
  --nofilesystem=host-etc \
  --nofilesystem=host-os \
  --filesystem=~/.themes:ro \
  --filesystem=~/.icons:ro \
  --filesystem=xdg-data/icons:ro \
  --filesystem=xdg-data/themes:ro \
  --filesystem=xdg-data/fonts:ro \
  --filesystem=xdg-config/gtk-3.0:ro \
  --filesystem=xdg-config/gtk-4.0:ro \
  --filesystem=xdg-config/Kvantum:ro \
  --filesystem=xdg-config/qt5ct:ro \
  --env=QT_STYLE_OVERRIDE=kvantum

flatpak override \
  --device=input \
  --device=dri \
  --allow=devel \
  --allow=multiarch \
  --allow=per-app-dev-shm \
  --filesystem=~/Me/Games \
  --filesystem=xdg-data/Steam \
  --filesystem=~/.var/app/com.valvesoftware.Steam/data/Steam \
  --filesystem=xdg-config/MangoHud:ro \
  --filesystem=xdg-config/vkBasalt:ro \
  --env=DXVK_ASYNC=1 \
  com.usebottles.bottles

flatpak override \
  --device=input \
  --device=dri \
  --allow=devel \
  --allow=multiarch \
  --allow=per-app-dev-shm \
  --filesystem=~/Me/Games \
  --filesystem=xdg-config/MangoHud:ro \
  --filesystem=xdg-config/vkBasalt:ro \
  --env=DXVK_ASYNC=1 \
  net.lutris.Lutris

flatpak override \
  --device=input \
  --device=dri \
  --allow=devel \
  --allow=multiarch \
  --allow=per-app-dev-shm \
  --filesystem=~/Me/Games \
  --filesystem=xdg-config/MangoHud:ro \
  --filesystem=xdg-config/vkBasalt:ro \
  --env=DXVK_ASYNC=1 \
  com.valvesoftware.Steam

flatpak override \
  --device=input \
  --device=dri \
  --allow=devel \
  --allow=multiarch \
  --allow=per-app-dev-shm \
  --filesystem=~/Me/Games \
  --filesystem=xdg-config/MangoHud:ro \
  --filesystem=xdg-config/vkBasalt:ro \
  --env=DXVK_ASYNC=1 \
  com.heroicgameslauncher.hgl

flatpak override \
  --device=input \
  --device=dri \
  --device=kvm \
  --allow=devel \
  --allow=multiarch \
  --allow=per-app-dev-shm \
  --filesystem=~/Me/Games \
  --filesystem=xdg-config/MangoHud:ro \
  --filesystem=xdg-config/vkBasalt:ro \
  --env=DXVK_ASYNC=1 \
  org.ryujinx.Ryujinx
fi

