#!/usr/bin/bash
source /usr/lib/catcat-os/funcvar.sh

# Remove useless logs, dirs or files
#

# System clean up
one_day=86400
one_week=$((one_day * 7))
twenty_days=$((one_day * 20))
cleanup_log="/etc/catcat-os/log/last_cleanup.log"
buttercare_log="/etc/catcat-os/log/buttercare.log"

ensure_file "${cleanup_log}" "${buttercare_log}"

if is_older_than "${cleanup_log}" "${one_week}"; then
    date "+%a %b %d %H:%M:%S %Y" > "${cleanup_log}"
    {
        /usr/bin/podman image prune -f
        /usr/bin/podman volume prune -f
        /usr/bin/systemd-tmpfiles --clean
        /usr/bin/rpm-ostree cleanup -bm
        /usr/bin/dnf5 clean all
        /usr/bin/flatpak --system uninstall --unused --assumeyes --noninteractive

        # Delete DNS logs older than 3 months (default}
        /usr/bin/localdnsctl -v --flush-logs
    } >> "${cleanup_log}"
fi

# Run buttercare trim every 20 days
if is_older_than "${buttercare_log}" "${twenty_days}"; then
    date "+%a %b %d %H:%M:%S %Y" > "${buttercare_log}"
    /usr/bin/buttercare -v balance trim >> "${buttercare_log}"
fi
