#!/bin/bash
shopt -s extglob
shopt -s nocasematch

FLATPAK_APPS="$(flatpak list --app)"

if [[ ! -f ~/.local/share/catcat-os/first-boot ]]; then

  # default configs for user home
  cp -PTr --update=none  /etc/skel/ ~/
  cp -PTr --update=none  /etc/skel/.config/ ~/.config/
  cp -PTr --update=none  /etc/skel/.local/ ~/.local/
  cp -PTr --update=none  /etc/skel/.shell.d/ ~/.shell.d/
  cp -PTr --update=none  /etc/skel/.var/ ~/.var/
  find ~/Me/ -maxdepth 2 -mindepth 1 -type f -name '*.gitkeep*' -delete
  
  [[ ! -d ~/.config/dconf.bak.og ]] && mv ~/.config/dconf ~/.config/dconf.bak.og
  mv ~/.config/dconf ~/.config/dconf.bak

  for i in $(ls -A1d /etc/dconf/db/distro.d/*);
  do
  dconf load / < $i;
  done

  mkdir -p ~/.local/share/catcat-os
  echo 'first boot' > ~/.local/share/catcat-os/first-boot

fi

# default configs for user home
cp -PTr --update=none  /etc/skel/ ~/
cp -PTr --update=none  /etc/skel/.config/ ~/.config/
cp -PTr --update=none  /etc/skel/.local/ ~/.local/
cp -PTr --update=none  /etc/skel/.shell.d/ ~/.shell.d/
cp -PTr --update=none  /etc/skel/.var/ ~/.var/

# gnome shell setup
DCONF_FOLDERS="$(dconf read /org/gnome/desktop/app-folders/folder-children)"
if [[ ! "${DCONF_FOLDERS}" =~ 'FileViewers' ]]; then
  [[ ! -d ~/.config/dconf.bak.og ]] && mv ~/.config/dconf ~/.config/dconf.bak.og
  mv ~/.config/dconf ~/.config/dconf.bak

  for i in $(ls -A1d /etc/dconf/db/distro.d/*);
  do
  dconf load / < $i;
  done
fi

[[ ! -f ~/.config/burn-my-windows/profiles/1679372508290696.conf ]] && cp -Pr /etc/skel/.config/burn-my-windows ~/.config/ && dconf write /org/gnome/shell/extensions/burn-my-windows/active-profile "'$HOME/.config/burn-my-windows/profiles/1679372508290696.conf'"

[ $(grep -c 'border-width: 1px' ~/.config/forge/stylesheet/forge/stylesheet.css) -lt 6 ] && cp -Pr /etc/skel/.config/forge/stylesheet/forge/stylesheet.css ~/.config/forge/stylesheet/forge/

cp -Prfu /etc/skel/.local/share/gnome-shell/* ~/.local/share/gnome-shell/
chmod 440 ~/.local/share/gnome-shell/extension-updates

# user dirs setup
! grep -q "$USER/Me/" ~/.config/user-dirs.dirs && cp -Pr /etc/skel/.config/user-dirs.dirs ~/.config/ 

! grep -q "$USER/Me/" ~/.config/gtk-3.0/bookmarks && sh -c "echo 'file://$HOME/Me Me
file://$HOME/Me/Documents Documents
file://$HOME/Me/Downloads Downloads
file://$HOME/Me/Pictures Pictures
file://$HOME/Me/Videos Videos
file://$HOME/Me/Music Music
file://$HOME/Me/Notes Notes
admin:/// /' > ~/.config/gtk-3.0/bookmarks"

# set folder icons
gio set ~/Me metadata::custom-icon-name "user-home"
gio set ~/Me/Backups metadata::custom-icon-name "folder-backup"
gio set ~/Me/Devel metadata::custom-icon-name "folder-code"
gio set ~/Me/Ebooks metadata::custom-icon-name "folder-books"
gio set ~/Me/Games metadata::custom-icon-name "folder-games"
gio set ~/Me/Notes metadata::custom-icon-name "folder-notes"
gio set ~/Me/Scripts metadata::custom-icon-name "folder-script"
gio set ~/Me/Secure metadata::custom-icon-name "folder-locked"
gio set ~/Me/Syncthing metadata::custom-icon-name "folder-syncthing"

# remove unnecessary directories
rmdir ~/Desktop ~/Downloads ~/Templates ~/Public ~/Documents ~/Music ~/Pictures ~/Videos
[[ ! -f ~/.mozilla/firefox/profiles.ini ]] && rm -rf ~/.mozilla
find ~/Me/ -maxdepth 2 -mindepth 1 -type f -name '*.gitkeep*' -delete

# shell setup
[ $(wc -l < ~/.config/fish/config.fish) -lt 4 ] && cp -Pr /etc/skel/.config/fish ~/.config/

! grep -q ".shell.d" ~/.bashrc && echo '
if [ -d ~/.shell.d ]; then
	for rc in ~/.shell.d/*; do
		if [ -f "$rc" ]; then
			. "$rc"
		fi
	done
fi

unset rc
' >> ~/.bash_profile

! grep -q "\[ -f ~/.bashrc \]" ~/.bash_profile && echo "[[ -f ~/.bashrc ]] && . ~/.bashrc" >> ~/.bash_profile


# theme flatpak apps
mkdir -p ~/.local/share/flatpak/overrides
! grep -q 'devices=!all' ~/.local/share/flatpak/overrides/global && echo '[Context]
devices=!all;
filesystems=!host;!host-etc;!host-os;~/.themes:ro;~/.icons:ro;xdg-data/icons:ro;xdg-data/themes:ro;xdg-data/fonts:ro;xdg-config/gtk-3.0:ro;xdg-config/gtk-4.0:ro;xdg-config/Kvantum:ro;xdg-config/qt5ct:ro;xdg-config/MangoHud:ro;xdg-config/vkBasalt:ro;

[Environment]
QT_STYLE_OVERRIDE=kvantum
' > ~/.local/share/flatpak/overrides/global

mkdir -p ~/.local/share/themes
mkdir -p ~/.local/share/icons
mkdir -p ~/.local/share/fonts

ln -srfT ~/.local/share/icons ~/.icons
ln -srfT ~/.local/share/themes ~/.themes

for dir in $(ls -A1d /usr/share/themes/{*Catppuccin*,*Lavanda*}); do cp -Prfu $dir ~/.local/share/themes/; done

# gedit setup
[[ ! -f ~/.var/app/org.gnome.gedit/data/libgedit-gtksourceview-300/styles/catppuccin-mocha.xml ]] && cp -Pr /etc/skel/.var/app/org.gnome.gedit ~/.var/app/

# vscodium setup
if ! ls -A1d ~/.vscode-oss/extensions/*atppuccin*; then
  codium --install-extension bierner.color-info
  codium --install-extension jeronimoekerdt.color-picker-universal
  codium --install-extension catppuccin.catppuccin-vsc
  codium --install-extension catppuccin.catppuccin-vsc-icons
  codium --install-extension ms-python.python
  codium --install-extension ms-toolsai.jupyter
  codium --install-extension redhat.vscode-yaml
  codium --install-extension huntertran.auto-markdown-toc
  codium --install-extension zaaack.markdown-editor
fi


# desktop files
[[ "${FLATPAK_APPS}" =~ 'steam' ]] && command -v steam && sed '$aNoDisplay=true' /usr/share/applications/steam.desktop > ~/.local/share/applications/steam.desktop

APP_ICON_TO_MODIFY=(
"io.freetubeapp.FreeTube /usr/share/icons/crafted/yt2.svg"
"io.gitlab.librewolf-community firefox"
"xyz.armcord.ArmCord discord"
)

for I in "${APP_ICON_TO_MODIFY[@]}"; do
  if [[ ! -f ~/.local/share/applications/${I%% *}.desktop ]]; then
    [[ "${FLATPAK_APPS}" =~ "${I%% *}" ]] && sed "s|^Icon=.*|Icon=${I#* }|" /var/lib/flatpak/exports/share/applications/${I%% *}.desktop > ~/.local/share/applications/${I%% *}.desktop
  fi
done

#gtk-update-icon-cache
#gtk4-update-icon-cache
###

