#!/usr/bin/bash
source /usr/lib/catcat/funcvar.sh
KARGS=$(rpm-ostree kargs)
NEEDED_KARGS=("")

COMMON_KARGS_TO_ADD=(
    "rd.udev.log_priority=3"
    "loglevel=3"
    "rd.shell=0"
    "rd.emergency=halt"
    "rd.luks.options=discard"
    "luks.options=discard"
)

for karg in "${COMMON_KARGS_TO_ADD[@]}"; do
    if [[ ! ${KARGS} =~ ${karg} ]]; then
        log "INFO" "Adding needed kargs: ${karg}"
        NEEDED_KARGS+=("--append-if-missing=${karg}")
    fi
done

if command -v nvidia-smi; then
    NEEDED_KARGS+=(
        "nvidia-drm.modeset=1"
        "nvidia-drm.fbdev=1"
        "rd.driver.blacklist=nouveau"
        "modprobe.blacklist=nouveau"
    )
fi

if [[ ${KARGS} =~ "nomodeset" ]]; then
    log "INFO" "Removing nomodeset"
    NEEDED_KARGS+=("--delete-if-present=nomodeset")
fi

if [[ -n "${NEEDED_KARGS}" ]]; then
    log "INFO" "Found needed karg changes, applying the following: ${NEEDED_KARGS[*]}"
    rpm-ostree kargs ${NEEDED_KARGS[*]} &
else
    log "INFO" "No karg changes needed"
fi
