#!/usr/bin/bash
source /usr/lib/catcat-os/funcvar.sh

BOOTC_KARGS="/usr/lib/bootc/kargs.d/catcat.toml"
EXISTING_KARGS="$(rpm-ostree kargs)"
NEEDED_KARGS=()

readarray -t COMMON_KARGS < <(grep '"' "${BOOTC_KARGS}" | cut -d '"' -f2)

for karg in "${COMMON_KARGS[@]}"; do
    if [[ ! "${EXISTING_KARGS}" =~ "${karg}" ]]; then
        NEEDED_KARGS+=("--append-if-missing=${karg}")
    fi
done

if [[ "${EXISTING_KARGS}" =~ "nomodeset" ]]; then
    log "INFO" "Removing nomodeset"
    NEEDED_KARGS+=("--delete-if-present=nomodeset")
fi

if [[ ${#NEEDED_KARGS[@]} -gt 0 ]]; then
    log "INFO" "Found needed karg changes, applying the following: ${NEEDED_KARGS[*]}"
    rpm-ostree kargs "${NEEDED_KARGS[@]}"
else
    log "INFO" "No karg changes needed"
fi
