#!/usr/bin/bash
source /usr/lib/catcat-os/funcvar.sh
one_day=86400
four_days=$((one_day * 4))
blocklist_autoupdate_log="/etc/catcat-os/log/auto-dns-blocklist-update.log"

ensure_file "${blocklist_autoupdate_log}"

if is_older_than "${blocklist_autoupdate_log}" "${four_days}"; then
    if check_network_connection; then
        date "+%a %b %d %H:%M:%S %Y" > "${blocklist_autoupdate_log}"
        localdnsctl -v --update | tee -a "${blocklist_autoupdate_log}"
        localdnsctl -v --restart | tee -a "${blocklist_autoupdate_log}"
    fi
else
    log "INFO" "Nothing to do."
    #log "INFO" "DNS blocklist updates after every $((four_days / 86400)) days."
    #log "INFO" "Use 'localdnsctl' command to update DNS blocklist manually."
fi
