#!/usr/bin/bash
source /usr/lib/catcat/funcvar.sh
one_day=86400
four_days=$((one_day * 4))
blocklist_autoupdate_log="/etc/catcat-os/log/auto-dns-blocklist-update.log"

if is_file_older ${four_days} "${blocklist_autoupdate_log}"; then
    date "+%a %b %d %H:%M:%S %Y" > "${blocklist_autoupdate_log}"
    localdnsctl -v --update | tee -a "${blocklist_autoupdate_log}"
    localdnsctl -v --restart | tee -a "${blocklist_autoupdate_log}"
else
    log "INFO" "Nothing to do."
    log "INFO" "DNS blocklist updates after every $((four_days / 86400)) days."
    log "INFO" "Use 'localdnsctl' command to update DNS blocklist manually."
fi
