#!/usr/bin/bash
source /usr/lib/catcat-os/bash-lib.sh

# Selinux fix
#restorecon  -vR /home/${U1000}/.local/share/icc
#restorecon -vR /etc/dnsmasq.d/
#restorecon -vR /var/log/usbguard
#restorecon -vR /var/lib/waydroid
#restorecon -vR /var/log/libvirt /var/lib/libvirt

# Support to run nix commands with sudo for user 1000
U1000="$(id -un 1000)"
nix_user_path="/home/${U1000}/.local/state/nix/profile/bin"
sudoersd_file="/etc/sudoers.d/nix-sudo-env"
if ! grep "${nix_user_path}" "${sudoersd_file}"; then
    log "INFO" "Adding support to run nix commands with sudo for user 1000"
    chmod -v 640 "${sudoersd_file}"
    sed -i "/secure_path = /s|$|:${nix_user_path}|" "${sudoersd_file}"
    # Correct sudoers.d perms
    chmod -v --recursive 440 "$(dirname "${sudoersd_file}")"
fi

# Mount tmpfs on /var/tmp
fstab_file="/etc/fstab"
if ! grep -E "^tmpfs .*/var/tmp .*tmpfs .*0 0$" "${fstab_file}"; then
    log "INFO" "Adding fstab entry to mount tmpfs on /var/tmp"
    printf "%-10s %-10s %-10s %-20s %s\n" "tmpfs" "/var/tmp" "tmpfs" \
        "defaults,noatime,mode=1777" "0 0" >> "${fstab_file}"
    systemctl daemon-reload && mount -a
fi

# Set ad-malware blocking localdns
/usr/bin/localdnsctl -v --setup

# TODO: Log unsuccessful login attempts
# Enabling needed authselect features
authsel_curr=$(authselect current)
if ! { grep "without-nullok" <<< "${authsel_curr}" &&
            grep "with-faillock" <<< "${authsel_curr}"; }; then
    #authselect select sssd
    authselect enable-feature without-nullok # Blocks empty password logins
    authselect enable-feature with-faillock # Enables account locking on failure
    authselect apply-changes
fi

# Usbguard setup
