name: build iso no fl

on:
  workflow_call:
  schedule:
    - cron: "0 0 1 * *" # Build & release ISOs every month

  workflow_dispatch:
    branches:
      - main
    paths:
      - '.github/workflows/build-iso.yml'

env:
  IMAGE_REGISTRY: ghcr.io/${{ github.repository_owner }}

concurrency:
  group: build-iso-${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build-iso:
    name: Build ISO
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    strategy:
      fail-fast: false
      matrix:
        image_name: ["catcat-os", "catcat-os-nv", "catcat-os-hh"]

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v5

      - name: Maximize build space
        uses: ublue-os/remove-unwanted-software@v9

      - name: Pre build configuration
        id: pre-build-config
        shell: bash
        run: |
          set -eou pipefail
          pwd
          ls -A1
          source ${{ github.workspace }}/files/VAR.sh
          echo "MAJOR_VERSION=${MAJOR_VERSION}" >> $GITHUB_ENV
          echo "DEFAULT_TAG=${DEFAULT_TAG}" >> $GITHUB_ENV
          echo "DATESTAMP=${DATESTAMP}" >> $GITHUB_ENV
          echo "TIMESTAMP=${TIMESTAMP}" >> $GITHUB_ENV

      - name: Build ISO
        uses: jasonn3/build-container-installer@v1.3.0
        id: build-iso
        with:
          arch: x86_64
          image_name: ${{ matrix.image_name }}
          image_repo: ${{ env.IMAGE_REGISTRY }}
          image_tag: ${{ env.DEFAULT_TAG }}
          variant: 'Kinoite'
          version: ${{ env.MAJOR_VERSION }}
          secure_boot_key_url: "https://github.com/ublue-os/bazzite/raw/main/secure_boot.der"
          enrollment_password: "universalblue"
          iso_name: ${{ matrix.image_name }}-no-fl-${{ env.MAJOR_VERSION }}-${{ env.DATESTAMP }}.iso
          enable_cache_dnf: "false"
          enable_cache_skopeo: "false"
          enable_flatpak_dependencies: "false"
          extra_boot_params: "rd.udev.log_priority=3 loglevel=3 processor.ignore_ppc=1 sysrq_always_enabled=1"
#          additional_templates: /github/workspace/files/scripts/setup-files/installer_defaults.tmpl

      - name: Move ISO to Upload Directory
        id: upload-directory
        shell: bash
        run: |
          ISO_UPLOAD_DIR=${{ github.workspace }}/upload
          mkdir ${ISO_UPLOAD_DIR}
          mv ${{ steps.build-iso.outputs.iso_path }}/${{ steps.build-iso.outputs.iso_name }} ${ISO_UPLOAD_DIR}
          mv ${{ steps.build-iso.outputs.iso_path }}/${{ steps.build-iso.outputs.iso_name }}-CHECKSUM ${ISO_UPLOAD_DIR}
          tree ${ISO_UPLOAD_DIR}
          echo "iso-upload-dir=${ISO_UPLOAD_DIR}" >> $GITHUB_OUTPUT

      - name: Upload ISOs and Checksum to Job Artifacts
        id: upload
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.image_name }}-iso
          path: ${{ steps.upload-directory.outputs.iso-upload-dir }}
          if-no-files-found: warn
          retention-days: 0
          compression-level: 0
          overwrite: true


