name: build images
on:
  workflow_call:
  schedule:
    - cron: '05 10 * * *'  # 10:05am UTC everyday
#  pull_request:
#    branches:
#      - main
#  push:
#    branches:
#      - main
#    paths-ignore:
#      - '**/README.md'
#      - '**/build-iso.yml'
#      - '**/create-release.yml'
  workflow_dispatch:

concurrency:
  group: build-image-${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build_push:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - IMAGE_NAME: catcat-os-nv
            BASE_IMAGE: ghcr.io/shriman-dev/catcat-os
            ALT_TAG: nvidia

          - IMAGE_NAME: catcat-os-hh
            BASE_IMAGE: ghcr.io/shriman-dev/catcat-os
            ALT_TAG: deck

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v7
        with:
          persist-credentials: false
          fetch-depth: 0

#      - name: Mount BTRFS for podman storage
#        uses: ublue-os/container-storage-action@911baca08baf30c8654933e9e9723cb399892140
#        with:
#          target-dir: /var/lib/containers
#          mount-opts: compress-force=zstd:12
#          loopback-free: "1"

#      - name: Maximize build space
#        uses: ublue-os/remove-unwanted-software@695eb75bc387dbcd9685a8e72d23439d8686cba6

      - name: Prepare environment
        id: prep-env
        shell: bash
        run: |
          set -euox pipefail
          lsblk --all -o +FSUSED,FSSIZE,LABEL,FSTYPE
          free -hm
          nproc --all
          pwd
          ls -A1
          podman images
          echo ${GITHUB_OUTPUT}
          cat ${GITHUB_ENV}

      - name: Build Image
        id: build-image
        env:
          IMAGE_NAME: ${{ matrix.IMAGE_NAME }}
          BASE_IMAGE: ${{ matrix.BASE_IMAGE }}
          ALT_TAG: ${{ matrix.ALT_TAG }}
          SBMOK_KEY: ${{ secrets.SBMOK_KEY }}
        shell: bash
        run: |
          set -euo pipefail
          source ${{ github.workspace }}/build/ENVAR
          builder() { sudo -E "${{ github.workspace }}/build/build.sh" "$@"; }
          builder build \
                  --image-name "${IMAGE_NAME}" \
                  --base-image "${BASE_IMAGE}" \
                  --alt-tag    "${ALT_TAG}"

      - name: Login to GitHub Container Registry
        if: github.event_name != 'pull_request' && github.ref == format('refs/heads/{0}', github.event.repository.default_branch)
        uses: docker/login-action@v4.5.1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push To GitHub Container Registry
        if: github.event_name != 'pull_request' && github.ref == format('refs/heads/{0}', github.event.repository.default_branch)
        id: push-image
        env:
          BUILD_TAGS: ${{ steps.build-image.outputs.build_tags }}
        shell: bash
        run: |
          set -euo pipefail
          source ${{ github.workspace }}/build/ENVAR
          declare -x BUILD_TAGS="${BUILD_TAGS}"
          builder() { sudo -E "${{ github.workspace }}/build/build.sh" "$@"; }
          builder push \
                  --image-name "${IMAGE_NAME}" \
                  --base-image "${BASE_IMAGE}" \
                  --alt-tag    "${ALT_TAG}"

      - name: Install Cosign
        if: github.event_name != 'pull_request' && github.ref == format('refs/heads/{0}', github.event.repository.default_branch)
        uses: sigstore/cosign-installer@v4.1.2
        with:
          cosign-release: "v2.6.3"

      - name: Sign container image
        if: github.event_name != 'pull_request' && github.ref == format('refs/heads/{0}', github.event.repository.default_branch)
        env:
          IMAGE_FULL: ${{ env.PUSH_REGISTRY }}/${{ matrix.IMAGE_NAME }}
          DIGEST: ${{ steps.push-image.outputs.digest }}
          COSIGN_EXPERIMENTAL: false
          COSIGN_PRIVATE_KEY: ${{ secrets.SIGNING_SECRET }}
        shell: bash
        run: |
          echo "Image Digest: ${DIGEST}"
          cosign sign -y --key env://COSIGN_PRIVATE_KEY ${IMAGE_FULL}@${DIGEST}
