name: Build All # Build Images, ISOs and make release
# Defines when the workflow will run
on:
  push:
    branches:
      - main                # Only runs on pushes to main branch
    paths-ignore:
      - '**/README.md'
  workflow_dispatch:        # Allows manual trigger of workflow

# Sets permissions for the workflow
permissions:
  contents: write           # Can modify repository contents
  packages: write           # Can publish packages
  id-token: write           # Can use OIDC tokens

# Prevents concurrent workflow runs
concurrency:
  group: build-all-${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true  # Cancels in-progress runs if a new one is triggered

jobs:
  build-main:
    name: Build Main
    uses: ./.github/workflows/build-image.yaml
    secrets: inherit        # Uses secrets from parent workflow

#  build-iso:
#    name: Build ISOs
#    needs: [build-main]
#    uses: ./.github/workflows/build-iso.yml
#    secrets: inherit

#  create-release:
#    name: Create Release
#    needs: [build-iso]  # Waits for check and ISO build
#    uses: ./.github/workflows/create-release.yml
