name: Build Images
on:
  workflow_call:
    inputs:
      image_name:
        required: false
        type: string
        default: catcat-os
      base_image:
        required: false
        type: string
        default: quay.io/fedora-ostree-desktops/silverblue
      img_flavor:
        required: false
        type: string
        default: main
#  schedule:
#    - cron: "00 6 * * *"    # build at 6:00 UTC every day
  workflow_dispatch:        # Allows manual trigger of workflow

jobs:
  build_image:
    name: ${{ inputs.image_name }}
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request' && github.ref == 'refs/heads/main'
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v7
        with:
          persist-credentials: false
          fetch-depth: 1

      - name: Maximize Build Space
        uses: hastd/free-disk-space@v0.1.2
        with:
          skip-if-available: "80G"

      - name: Mount Container Storage BTRFS Loopback
        shell: bash
        run: |
          sudo truncate -s 75G /mnt/podman-storage.img
          sudo mkfs.btrfs -f -m single -d single /mnt/podman-storage.img
          sudo podman system reset --force
          sudo systemctl stop podman.service
          LOOP=$(sudo losetup --find --show --direct-io=on /mnt/podman-storage.img)
          sudo mkdir -p /mnt/podman-storage
          sudo mount -o compress-force=zstd:2,discard=async,noatime "${LOOP}" /mnt/podman-storage
          sudo mkdir -p /mnt/podman-storage/{storage,tmp}
          sudo mount --bind /mnt/podman-storage/storage /var/lib/containers/storage
          sudo systemctl start podman.service

      - name: Prepare Environment
        id: prep-env
        shell: bash
        run: |
          set -euox pipefail
          id
          lsblk --all -o +FSUSED,FSSIZE,LABEL,FSTYPE
          free -hm
          nproc --all
          pwd
          ls -A1

      - name: Build Image
        id: build-image
        env:
          SBMOK_KEY: ${{ secrets.SBMOK_KEY }}
          IMAGE_NAME: ${{ inputs.image_name }}
          BASE_IMAGE: ${{ inputs.base_image }}
          IMG_FLAVOR: ${{ inputs.img_flavor }}
        shell: bash
        run: |
          set -euo pipefail
          source "${GITHUB_WORKSPACE}/build/ENVAR"
          sudo -E "${GITHUB_WORKSPACE}/build/builder" \
                build --image-name "${IMAGE_NAME}" \
                      --base-image "${BASE_IMAGE}" \
                      --img-flavor "${IMG_FLAVOR}"

      - name: Chunk Image
        id: chunk-image
        env:
          IMAGE_NAME: ${{ inputs.image_name }}
          BASE_IMAGE: ${{ inputs.base_image }}
        shell: bash
        run: |
          set -euo pipefail
          source "${GITHUB_WORKSPACE}/build/ENVAR"
          sudo -E "${GITHUB_WORKSPACE}/build/builder" \
                chunk --image-name "${IMAGE_NAME}" \
                      --base-image "${BASE_IMAGE}"

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v4.6.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push To GitHub Container Registry
        id: push-image
        env:
          build_tags: ${{ steps.build-image.outputs.build_tags }}
          IMAGE_NAME: ${{ inputs.image_name }}
          IMG_FLAVOR: ${{ inputs.img_flavor }}
        shell: bash
        run: |
          set -euo pipefail
          source "${GITHUB_WORKSPACE}/build/ENVAR"
          declare -x BUILD_TAGS="${build_tags}"
          sudo -E "${GITHUB_WORKSPACE}/build/builder" \
                push --image-name "${IMAGE_NAME}" \
                     --img-flavor "${IMG_FLAVOR}" \
                     --compression-format "zstd" \
                     --compression-level 19 \

      - name: Install Cosign
        uses: sigstore/cosign-installer@v4.1.2
        with:
          use-sudo: true
          install-dir: /usr/bin
          cosign-release: "v2.6.3"

      - name: Sign Container Image
        env:
          COSIGN_PRIVATE_KEY: ${{ secrets.SIGNING_SECRET }}
          IMAGE_NAME: ${{ inputs.image_name }}
        shell: bash
        run: |
          set -euo pipefail
          source "${GITHUB_WORKSPACE}/build/ENVAR"
          sudo -E "${GITHUB_WORKSPACE}/build/builder" \
                cosign --image-name "${IMAGE_NAME}"
